name: StableRadio-iOS
options:
  bundleIdPrefix: com.stableradio
  deploymentTarget:
    iOS: "12.0"

packages:
  StableRadioCore:
    path: ../StableRadioCore

targets:
  StableRadio-iOS:
    type: application
    platform: iOS
    sources:
      - path: StableRadio-iOS
        excludes:
          - "*.md"
    dependencies:
      - package: StableRadioCore
    info:
      path: Info.plist
      properties:
        CFBundleName: StableRadio
        CFBundleDisplayName: StableRadio
        CFBundleIdentifier: com.stableradio.ios
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSRequiresIPhoneOS: YES
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocalNetworkUsageDescription: "StableRadio needs local network access to discover and receive audio from macOS senders."
        NSBonjourServices:
          - "_stableradio._udp"
    settings:
      base:
        PRODUCT_NAME: StableRadio
        PRODUCT_BUNDLE_IDENTIFIER: com.stableradio.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.5"
        IPHONEOS_DEPLOYMENT_TARGET: "12.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
