name: StableRadio-macOS
options:
  bundleIdPrefix: com.stableradio
  deploymentTarget:
    macOS: "11.0"

packages:
  StableRadioCore:
    path: ../StableRadioCore

targets:
  StableRadio-macOS:
    type: application
    platform: macOS
    sources:
      - path: StableRadio-macOS
        excludes:
          - "*.md"
    dependencies:
      - package: StableRadioCore
    info:
      path: Info.plist
      properties:
        CFBundleName: StableRadio
        CFBundleDisplayName: StableRadio
        CFBundleIdentifier: com.stableradio.macos
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "11.0"
        NSMicrophoneUsageDescription: "StableRadio needs microphone access to capture and broadcast audio to iOS devices."
        NSLocalNetworkUsageDescription: "StableRadio needs local network access to discover and stream audio to iOS receivers."
        NSBonjourServices:
          - "_stableradio._udp"
        NSHumanReadableCopyright: "Copyright © 2026. All rights reserved."
    settings:
      base:
        PRODUCT_NAME: StableRadio
        PRODUCT_BUNDLE_IDENTIFIER: com.stableradio.macos
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.5"
        MACOSX_DEPLOYMENT_TARGET: "11.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
